version: '3'
services:
  varnishstatbeat:
    build: .
    ports:
      - 8080:8080
    depends_on:
      - elasticsearch
    links:
      - elasticsearch
      - backend
    image: varnishstatbeat
  backend:
    image: nginx:latest
    ports:
      - 80:80
    environment:
      - NGINX_HOST=backend
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.4.3
    ports:
      - 9200:9200
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
  kibana:
    image: docker.elastic.co/kibana/kibana:5.4.3
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch
